spring:
  application:
    name: auth

  webflux:
    base-path: /api

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${HOST}:27017/${MONGO_DB_NAME}?authSource=admin
      uuid-representation: standard

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration