spring:
  application:
    name: Agents-Scheduling-MCP

  datasource:
    url: jdbc:postgresql://localhost:5432/memory
    username: br7forlife
    password: 12345
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop

  ai:
    ollama: 
      init:
        pull-model-strategy: when-missing
        
      base-url: http://localhost:11434
      chat:   
        model: qwen2.5:3b
        num-thread: 5
        num-ctx: 1024
        num-keep: 0
        

